---
- name: build go-ipfs Docker image
  include_tasks:
    file: build.yml
    apply:
      delegate_to: localhost

- name: copy docker image to server
  become: no
  copy: src="/tmp/go-ipfs-{{ go_ipfs_version }}.tar" dest="/tmp/go-ipfs-{{ go_ipfs_version }}.tar"

- name: Load image from archive
  docker_image:
    name: "go-ipfs"
    tag: "{{ go_ipfs_version }}"
    load_path: "/tmp/go-ipfs-{{ go_ipfs_version }}.tar"
    source: load


- name: Start go-ipfs container
  docker_container:
    name: "go-ipfs"
    image: "go-ipfs:{{ go_ipfs_version }}"
    network_mode: host
    state: started
    command: "{{ go_ipfs_cmd }}"
    env: "{{ go_ipfs_env }}"
    comparisons:
      env: strict
