---
# install node_exporter
- name: check current node_exporter ref
  shell: "cat /opt/node_exporter.ref | grep {{ node_exporter_ref }}"
  ignore_errors: true
  register: node_exporter_ref_present

- name: clone node_exporter.git
  git:
    repo: https://github.com/prometheus/node_exporter.git
    dest: /opt/node_exporter
    version: "{{ node_exporter_ref }}"
  when: "node_exporter_ref_present.rc != 0"

- name: build node_exporter
  shell: "rm -rf .build && make && make test chdir=/opt/node_exporter"
  when: "node_exporter_ref_present.rc != 0"

- name: install node_exporter
  file:
    src: /opt/node_exporter/node_exporter
    dest: /usr/bin/node_exporter
    state: link
  when: "node_exporter_ref_present.rc != 0"

- name: install upstart script
  template:
    src: upstart_node_exporter.conf.j2
    dest: /etc/init/node_exporter.conf
  register: upstart_node_exporter

- name: restart node_exporter
  service:
    name: node_exporter
    state: restarted
  when: "node_exporter_ref_present.rc != 0 or upstart_node_exporter.changed"

- name: record new node_exporter ref
  shell: "echo {{ node_exporter_ref }} > /opt/node_exporter.ref"
  when: "node_exporter_ref_present.rc != 0"

# install blackbox_exporter
- file:
    path: /opt/blackbox_exporter/config
    state: directory
- template:
    src: blackbox_exporter.yml.j2
    dest: /opt/blackbox_exporter/config/blackbox.yml
    mode: 0400
  register: blackbox_exporter_yml

- docker:
    name: blackbox_exporter
    image: "prom/blackbox-exporter:{{ blackbox_exporter_ref }}"
    command: -config.file=/config/blackbox.yml -web.listen-address=127.0.0.1:9115
    state: reloaded
    restart_policy: always
    net: host
    volumes:
    - /opt/blackbox_exporter/config:/config

- docker:
    name: blackbox_exporter
    image: "prom/blackbox-exporter:{{ blackbox_exporter_ref }}"
    state: restarted
  when: "blackbox_exporter_yml.changed"
