---
- name: "copy httpasswd"
  no_log: true
  copy:
    force: yes
    dest: "{{ nginx_conf_path }}/passwd/.httpasswd-node-exporter"
    mode: 0644
    owner: root
    group: root
    content: "admin:{PLAIN}{{ vault_node_exporter_password }}"
  notify:
    - "Restart_Nginx"

- name: copy nginx configs
  become: yes
  copy:
    src: "{{ role_path }}/files/"
    dest: "{{ nginx_conf_path }}/"
    force: yes
  notify:
    - "Restart_Nginx"
