---
- name: check docker
  command: docker -v
  ignore_errors: true
  register: docker_present
- name: copy get.docker.io script
  copy: src=get-docker.sh dest=/tmp
  when: docker_present.rc != 0
- name: install docker
  shell: cat /tmp/get-docker.sh | sh
  when: docker_present.rc != 0

- name: "copy pip install file"
  copy: src=get-pip.py dest=/tmp/get-pip.py
- name: "install pip"
  shell: "python /tmp/get-pip.py"
- name: "install docker-py"
  pip: name=docker-py version=0.5.3

- name: "create directory for containers"
  file: path=/containers state=directory
