---
- name: check docker
  command: docker -v
  ignore_errors: true
  register: docker_present
- name: copy get.docker.io script
  copy: src=get-docker.sh dest=/tmp
  when: docker_present.rc != 0
- name: install docker
  shell: cat /tmp/get-docker.sh | sh
  when: docker_present.rc != 0

- name: "copy pip install file"
  copy: src=get-pip.py dest=/tmp/get-pip.py
- name: "install pip"
  shell: "python /tmp/get-pip.py"
- name: "install docker-py"
  pip: name=docker-py version=1.5.0

- name: "create directory for containers"
  file: path=/containers state=directory

- name: MIGRATION remove bogus config line
  lineinfile:
    dest: /etc/default/docker
    line: DOCKER_OPTS=--log-driver=none
    state: absent
  notify:
    - restart docker
- name: MIGRATION remove bogus config line no. 2
  lineinfile:
    dest: /etc/default/docker
    line: 'DOCKER_OPTS="$DOCKER_OPTS --log-driver=none"'
    state: absent
  notify:
    - restart docker
- name: container log rotation
  lineinfile:
    dest: /etc/default/docker
    regexp: ^DOCKER_OPTS=
    line: 'DOCKER_OPTS="$DOCKER_OPTS --log-driver=json-file --log-opt max-size=100m --log-opt max-file=2"'
    state: present
  notify:
    - restart docker

- apt:
    name: lxc-docker
    state: latest

- name: docker service
  service:
    name: docker
    enabled: yes
    state: started
