---
- authorized_key: 'user=root key="{{ item }}"'
  with_items: "{{ authorized_keys }}"
- command: apt-get install -y mosh vim htop screen bridge-utils build-essential autoconf libtool bison flex nodejs
- file:
    src: /usr/bin/nodejs
    path: /usr/bin/node
    state: link
    mode: 755
