---
- hostname: "name={{ inventory_hostname }}"
- shell: "apt-get update && apt-get install -y mosh vim htop screen bridge-utils build-essential autoconf libtool bison flex nodejs npm mercurial git sysstat iftop tmux unzip jq gdb tree"
- file:
    src: /usr/bin/nodejs
    path: /usr/bin/node
    state: link
    mode: 755
