---
- name: include dns vars
  include_vars: "dns.yml"

# renew gateway cert
- include: renew.yml
    dns_alt_names="{{ gateway_dns_alt_names }}"
    cert_path="/etc/nginx/tmp/gateway.crt"
    trustchain_path="/etc/nginx/tmp/trustchain.pem"
