---
- name: check current cjdns ref
  shell: "cat /opt/cjdns.ref | grep {{ cjdns_ref }}"
  ignore_errors: true
  register: cjdns_ref_present

- name: clone cjdns.git
  git:
    repo: https://github.com/hyperboria/cjdns.git
    dest: /opt/cjdns
    version: "{{ cjdns_ref }}"
    force: yes
  when: "cjdns_ref_present.rc != 0"

- name: build cjdns
  shell: "./clean && ./do chdir=/opt/cjdns"
  when: "cjdns_ref_present.rc != 0"

- name: install cjdroute
  shell: "mv /usr/bin/cjdroute /usr/bin/cjdroute.old ; cp /opt/cjdns/cjdroute /usr/bin/"
  when: "cjdns_ref_present.rc != 0"

- name: install cjdroute.conf
  template:
    src: cjdroute.conf.j2
    dest: /etc/cjdroute.conf
    mode: 0400
  register: cjdroute_conf

- name: install upstart script
  template:
    src: cjdns.conf
    dest: /etc/init/cjdns.conf
    mode: 0644
  register: cjdns_conf

- name: restart cjdroute
  service:
    name: cjdns
    state: restarted
    enabled: yes
  when: "cjdns_ref_present.rc != 0 or cjdroute_conf.changed or cjdns_conf.changed"

- name: record new cjdns ref
  shell: "echo {{ cjdns_ref }} > /opt/cjdns.ref"
  when: "cjdns_ref_present.rc != 0"
