---
- name: "copy SSL certs"
  # no_log: true
  copy:
    force: yes
    dest: "/etc/nginx/{{ item.location }}"
    mode: 0644
    owner: root
    group: root
    content: "{{ item.content }}"
  with_items:
    - { location: "websites.crt", content: "{{ vault_gateway_websites_cert }}"}
    - { location: "websites.key", content: "{{ vault_gateway_websites_key }}"}
  notify:
    - "Restart_Nginx"
