---
- hosts: jenkins
  vars:
      do:
          DO_API_KEY: "{{ lookup('env','DIGITAL_OCEAN_API_KEY') }}"
          DO_CLIENT_ID: "{{  lookup('env','DIGITAL_OCEAN_CLIENT_ID') }}"
  tasks:
    - name: "install dopy"
      pip: name=dopy
    - environment: do
      digital_ocean_domain:
        state: present
        name: uranus.nyc.srv.protocol-dev.com
        ip: 162.243.248.213
    - environment: do
      digital_ocean_domain:
        state: present
        name: pluto.sfo.srv.protocol-dev.com
        ip: 104.236.179.241
    - environment: do
      digital_ocean_domain:
        state: present
        name: neptune.sfo.srv.protocol-dev.com
        ip: 104.236.176.52
    - environment: do
      digital_ocean_domain:
        state: present
        name: saturn.sg.srv.protocol-dev.com
        ip: 128.199.219.111
    - environment: do
      digital_ocean_domain:
        state: present
        name: jupiter.sfo.srv.protocol-dev.com
        ip: 104.236.175.101

    - environment: do
      digital_ocean_domain:
        state: present
        name: uranus.srv.protocol-dev.com
        ip: 162.243.248.213
    - environment: do
      digital_ocean_domain:
        state: present
        name: pluto.srv.protocol-dev.com
        ip: 104.236.179.241
    - environment: do
      digital_ocean_domain:
        state: present
        name: neptune.srv.protocol-dev.com
        ip: 104.236.176.52
    - environment: do
      digital_ocean_domain:
        state: present
        name: saturn.srv.protocol-dev.com
        ip: 128.199.219.111
    - environment: do
      digital_ocean_domain:
        state: present
        name: jupiter.srv.protocol-dev.com
        ip: 104.236.175.101

    - environment: do
      digital_ocean_domain:
        state: present
        name: uranus.i.ipfs.io
        ip: 162.243.248.213
    - environment: do
      digital_ocean_domain:
        state: present
        name: pluto.i.ipfs.io
        ip: 104.236.179.241
    - environment: do
      digital_ocean_domain:
        state: present
        name: neptune.i.ipfs.io
        ip: 104.236.176.52
    - environment: do
      digital_ocean_domain:
        state: present
        name: saturn.i.ipfs.io
        ip: 128.199.219.111
    - environment: do
      digital_ocean_domain:
        state: present
        name: jupiter.i.ipfs.io
        ip: 104.236.175.101

    - environment: do
      digital_ocean_domain:
        state: present
        name: mercury.i.ipfs.io
        ip: 178.62.61.185
    - environment: do
      digital_ocean_domain:
        state: present
        name: earth.i.ipfs.io
        ip: 178.62.158.247
    - environment: do
      digital_ocean_domain:
        state: present
        name: venus.i.ipfs.io
        ip: 104.236.76.40

    - environment: do
      digital_ocean_domain:
        state: present
        name: mars.i.ipfs.io
        ip: 104.131.131.82
