---
- name: fetch GIT repo
  block:
    - name: fetch GIT repo
      become: no
      git:
        repo: "git@github.com:ipfs/go-ipfs.git"
        force: yes
        update: yes
        dest: "/tmp/go-ipfs/{{ go_ipfs_version }}"
        version: '{{ go_ipfs_version }}'
  rescue:
    - name: RESCUE - remove GIT repo dir
      file:
        state: absent
        path: "/tmp/go-ipfs/{{ go_ipfs_version }}"
    - name: RESCUE - retry fetch GIT repo
      become: no
      git:
        repo: "git@github.com:ipfs/go-ipfs.git"
        force: yes
        update: yes
        dest: "/tmp/go-ipfs/{{ go_ipfs_version }}"
        version: '{{ go_ipfs_version }}'


- name: Build base image
  become: no
  docker_image:
    name: "go-ipfs-ansible:{{ go_ipfs_version }}"
    build:
      path: "/tmp/go-ipfs/{{ go_ipfs_version }}"
      pull: yes
    source: build
