---
# logrotate won't run parent directory has insecure permissions (It's world writable or writable by group which is not "root")
- name: set correct /var/log permissions for logrotate
  file:
    path: /var/log
    owner: root
    group: root
    state: directory
    mode: '0775'

- name: set permissions for ipfs log file
  file:
    path: /var/log/ipfs
    state: touch
    owner: syslog
    group: root
    mode: '0664'
    modification_time: preserve
    access_time: preserve

- name: copy ipfs rsyslogd config
  copy:
    src: "etc/rsyslog.conf"
    dest: "/etc/rsyslog.conf"
    force: yes
  notify:
    - "Restart_RSYSLOG"

- name: copy ipfs rsyslogd config
  copy:
    src: "etc/rsyslog.d/42-ipfs.conf"
    dest: "/etc/rsyslog.d/42-ipfs.conf"
    force: yes
  notify:
    - "Restart_RSYSLOG"

- name: copy ipfs logrotate config
  template:
    src: "etc/logrotate.d/ipfs.j2"
    dest: "/etc/logrotate.d/ipfs"
    force: yes
