---
- name: container log rotation
  lineinfile:
    dest: /etc/default/docker
    regexp: ^DOCKER_OPTS=
    line: 'DOCKER_OPTS="$DOCKER_OPTS --log-driver=json-file --log-opt max-size=100m --log-opt max-file=2"'
    state: present
  notify:
    - restart docker

- apt:
    name: lxc-docker
    state: latest

- name: docker service
  service:
    name: docker
    enabled: yes
    state: started
