---
- hosts: all
  pre_tasks:
    - include_vars: secrets_plaintext/secrets.yml
  roles:
    - node_exporter

- hosts: metrics
  vars:
    node_targets: "{{ cjdns_identities.keys() }}"
    gateway_targets: "{{ groups.gateway }}"
    storage_targets: "{{ groups.storage }}"
    metrics_targets: "{{ groups.metrics }}"
    probers: "{{ groups.metrics + groups.util }}"
  pre_tasks:
    - include_vars: secrets_plaintext/secrets.yml
  roles:
    - metrics
