---
- hosts: util
  vars:
    pinbot_targets: "{{ groups.gateway }}"
  pre_tasks:
    - include_vars: secrets_plaintext/secrets.yml
  handlers:
    - include: roles/nginx/handlers/main.yml
  roles:
    - pinbot
