---
- hosts: preloaders
  remote_user: "{{ deploy_user }}"
  roles:
    - role: ssh-keys
      ssh_user: "{{ deploy_user }}"
    - role: geerlingguy.docker
      docker_install_compose: false
    - role: python-dependencies
  vars_files:
    - ../secrets_secure/vault.yml

- hosts: preloaders
  serial: 1
  remote_user: "{{ deploy_user }}"
  roles:
    - role: go-ipfs-deploy-bin
  vars_files:
    - ../secrets_secure/vault.yml
