---
# create/update config
- file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /opt/prometheus/config
  - /opt/prometheus/data
  - /opt/grafana/config
  - /opt/grafana/data
- template:
    src: prometheus.yml.j2
    dest: /opt/prometheus/config/prometheus.yml
    mode: 0400
  register: prometheus_yml
- template:
    src: grafana.ini.j2
    dest: /opt/grafana/config/grafana.ini
    mode: 0400
  register: grafana_ini

# build the prometheus docker image, if needed
- shell: "cat /opt/prometheus.ref | grep {{ prometheus_ref }}"
  ignore_errors: true
  register: prometheus_ref_present
- git:
    repo: https://github.com/prometheus/prometheus.git
    dest: /opt/prometheus/src
    version: "{{ prometheus_ref }}"
  when: "prometheus_ref_present.rc != 0"
- copy:
    src: Dockerfile
    dest: /opt/prometheus/Dockerfile
  when: "prometheus_ref_present.rc != 0"
- shell: "docker build -t prometheus:{{ prometheus_ref }} /opt/prometheus"
  when: "prometheus_ref_present.rc != 0"
- shell: "echo {{ prometheus_ref }} > /opt/prometheus.ref"
  when: "prometheus_ref_present.rc != 0"

# assert containers run and are up-to-date
- docker:
    name: prometheus
    image: "prometheus:{{ prometheus_ref }}"
    state: reloaded
    restart_policy: always
    net: host
    volumes:
    - /opt/prometheus/config:/etc/prometheus
    - /opt/prometheus/data:/prometheus
- docker:
    name: grafana
    image: "luzifer/grafana-prometheus:{{ grafana_ref }}"
    state: reloaded
    restart_policy: always
    ports:
    - 127.0.0.1:3000:3000
    volumes:
    - /opt/grafana/config:/etc/grafana
    - /opt/grafana/data:/var/lib/grafana

# apply config updates
- docker:
    name: prometheus
    image: "prometheus:{{ prometheus_ref }}"
    state: restarted
  when: "prometheus_yml.changed"
- docker:
    name: grafana
    image: "luzifer/grafana-prometheus:{{ grafana_ref }}"
    state: restarted
  when: "grafana_ini.changed"

# nginx vhost
- file: path=/containers/ipfs_gateway_proxy state=directory
- file: path=/containers/ipfs_gateway_proxy/conf.d state=directory
- template:
    src: metrics.conf.j2
    dest: /containers/ipfs_gateway_proxy/conf.d/metrics.conf
  register: nginx_metrics_conf
- command: docker exec ipfs_gateway_proxy /etc/init.d/nginx reload
  when: nginx_metrics_conf.changed
