---
- hosts: all
  pre_tasks:
    - include_vars: secrets_plaintext/secrets.yml
  handlers:
    - include: roles/nginx/handlers/main.yml
  roles:
    - node_exporter

- hosts: metrics
  vars:
    gateway_group: gateway
  pre_tasks:
    - include_vars: secrets_plaintext/secrets.yml
  handlers:
    - include: roles/nginx/handlers/main.yml
  roles:
    - metrics
