---
- hosts: all
  pre_tasks:
    - include_vars: secrets_plaintext/secrets.yml
  handlers:
    - include: roles/nginx/handlers/main.yml
  roles:
    - node_exporter

- hosts: metrics
  vars:
    node_targets: "{{ cjdns_identities.keys() }}"
    gateway_targets: "{{ groups.gateway }}"
    storage_targets: "{{ groups.storage }}"
    metrics_targets: "{{ metrics.storage }}"
  pre_tasks:
    - include_vars: secrets_plaintext/secrets.yml
  handlers:
    - include: roles/nginx/handlers/main.yml
  roles:
    - metrics
