---
- hosts: all
  pre_tasks:
  - include_vars: secrets.yml
  roles:
    - common
    - docker
    - cjdns
    - nginx
    - node_exporter

- hosts: gateway
  vars:
    gateway_group: gateway
  pre_tasks:
    - include_vars: secrets.yml
  handlers:
    - include: roles/nginx/handlers/main.yml
  roles:
    - ipfs
    - ipfs_gateway

- hosts: pluto
  pre_tasks:
  - include_vars: secrets.yml
  handlers:
  - include: roles/nginx/handlers/main.yml
  roles:
  - metrics

- hosts:
    - pluto
    - neptune
  vars:
    gateway_group: gateway
  pre_tasks:
    - include_vars: secrets.yml
  roles:
    - pinbot
