---
- hosts: all
  vars:
    gateway_group: all
  pre_tasks:
  - include_vars: secrets.yml
  roles:
    - common
    - cjdns
    - ipfs
    - ipfs_gateway

- hosts: pluto
  pre_tasks:
  - include_vars: secrets.yml
  roles:
  - metrics
