---
- hosts: storage:!sirius:!castor
  pre_tasks:
    - include_vars: secrets_plaintext/secrets.yml
  tasks:
    - user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        home: "{{ item.home }}"
        group: users
        state: present
      with_items: "{{ users }}"
    - authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.key }}"
        state: present
        exclusive: yes
      with_items: "{{ users }}"
# XXX migration: disable logins in order to deprecate castor
- hosts: castor
  pre_tasks:
    - include_vars: secrets_plaintext/secrets.yml
  tasks:
    - authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.key }}"
        state: absent
      with_items: "{{ users }}"
