---
- name: create config directory
  file: path=/opt/nginx/conf.d state=directory
- name: create certs directory
  file: path=/opt/nginx/certs state=directory
- name: install config
  template:
    src: nginx.conf.j2
    dest: /opt/nginx/conf.d/nginx.conf
  notify:
    - reload nginx
- name: run
  docker:
    state: reloaded
    name: nginx
    image: "nginx:{{ nginx_version }}"
    volumes:
      - /opt/nginx/conf.d:/etc/nginx/conf.d
      - /opt/nginx/certs:/etc/nginx/certs
      - /opt/nginx/logs:/var/log/nginx
    net: host
    restart_policy: always
